FROM node:latest

# Set working directory to the root of your project
WORKDIR /usr/src/ServerDir

# Copy dependencies
COPY package*.json ./
RUN npm install express dotenv cors jsonwebtoken

# Copy the entire source
COPY . .

# Documentation only
EXPOSE 8080

# The command in docker-compose.yml will override any CMD here,
# but it's good practice to have a default:
CMD ["node", "src/Web_Server/app.js"]